name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sonarr_version:
        description: 'Sonarr version to build (default: latest)'
        required: false
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Sonarr version
        id: sonarr_version
        run: |
          echo "🔍 Determining Sonarr version to build..."
          
          # Check if manual version override is provided
          if [ "${{ github.event.inputs.sonarr_version }}" != "" ] && [ "${{ github.event.inputs.sonarr_version }}" != "latest" ]; then
            SONARR_VERSION="${{ github.event.inputs.sonarr_version }}"
            echo "📌 Using manually specified version: ${SONARR_VERSION}"
          else
            # Read version from VERSION file
            if [ -f VERSION ]; then
              source VERSION
              echo "📄 Read version from VERSION file: ${SONARR_VERSION}"
            else
              echo "❌ VERSION file not found!"
              exit 1
            fi
          fi
          
          # Validate version format
          if [[ ! "$SONARR_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Invalid version format: ${SONARR_VERSION}"
            echo "   Expected format: X.X.X.X (e.g., 4.0.14.2939)"
            exit 1
          fi
          
          echo "✅ Will build Sonarr version: ${SONARR_VERSION}"
          echo "version=${SONARR_VERSION}" >> $GITHUB_OUTPUT
          echo "actual_version=${SONARR_VERSION}" >> $GITHUB_OUTPUT

      - name: Generate build date
        id: date
        run: |
          BUILD_DATE=$(date +'%Y-%m-%d')
          echo "📅 Build date: ${BUILD_DATE}"
          echo "date=${BUILD_DATE}" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.sonarr_version.outputs.actual_version }}-${{ steps.date.outputs.date }},enable={{is_default_branch}}
            type=ref,event=pr

      - name: Display build information
        run: |
          echo "🏗️ Build Information:"
          echo "   Registry: ${{ env.REGISTRY }}"
          echo "   Image: ${{ env.IMAGE_NAME }}"
          echo "   Sonarr Version: ${{ steps.sonarr_version.outputs.actual_version }}"
          echo "   Build Date: ${{ steps.date.outputs.date }}"
          echo "   Event: ${{ github.event_name }}"
          echo ""
          echo "🏷️ Tags to be created:"
          echo "${{ steps.meta.outputs.tags }}" | while read tag; do
            echo "   - ${tag}"
          done
          echo ""
          echo "📦 Build Args:"
          echo "   SONARR_VERSION=${{ steps.sonarr_version.outputs.version }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SONARR_VERSION=${{ steps.sonarr_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max