name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      sonarr_version:
        description: 'Sonarr version to build (default: latest)'
        required: false
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Sonarr version
        id: sonarr_version
        run: |
          if [ "${{ github.event.inputs.sonarr_version }}" != "" ]; then
            SONARR_VERSION="${{ github.event.inputs.sonarr_version }}"
          else
            SONARR_VERSION="latest"
          fi
          echo "version=${SONARR_VERSION}" >> $GITHUB_OUTPUT
          
          # Get actual version number from LinuxServer API
          ACTUAL_VERSION=$(curl -s "https://api.linuxserver.io/api/v1/images" | jq -r '.data.repositories.linuxserver[] | select(.name == "sonarr") | .version' | sed 's/-.*//')
          if [ -z "$ACTUAL_VERSION" ]; then
            ACTUAL_VERSION="unknown"
          fi
          echo "actual_version=${ACTUAL_VERSION}" >> $GITHUB_OUTPUT

      - name: Generate build date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.sonarr_version.outputs.actual_version }}-${{ steps.date.outputs.date }},enable={{is_default_branch}}
            type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SONARR_VERSION=${{ steps.sonarr_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max