name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Sonarr version
        id: sonarr_version
        run: |
          echo "🔍 Determining Sonarr version to build..."
          
          # Read version from VERSION file
          if [ -f VERSION ]; then
            source VERSION
            echo "📄 Read version from VERSION file: ${SONARR_VERSION}"
          else
            echo "❌ VERSION file not found!"
            exit 1
          fi
          
          echo "✅ Will build Sonarr version: ${SONARR_VERSION}"
          echo "version=${SONARR_VERSION}" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.sonarr_version.outputs.version }},enable={{is_default_branch}}
            type=raw,value=${{ steps.sonarr_version.outputs.version }}-${{ github.run_number }},enable={{is_default_branch}}
            type=ref,event=pr

      - name: Display build information
        run: |
          echo "🏗️ Build Information:"
          echo "   Registry: ${{ env.REGISTRY }}"
          echo "   Image: ${{ env.IMAGE_NAME }}"
          echo "   Sonarr Version: ${{ steps.sonarr_version.outputs.version }}"
          echo "   Build number: ${{ github.run_number }}"
          echo "   Event: ${{ github.event_name }}"
          echo ""
          echo "🏷️ Tags to be created:"
          echo "${{ steps.meta.outputs.tags }}" | while read tag; do
            echo "   - ${tag}"
          done
          echo ""
          echo "📦 Build Args:"
          echo "   SONARR_VERSION=${{ steps.sonarr_version.outputs.version }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SONARR_VERSION=${{ steps.sonarr_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
